### PR TITLE
Add Better Fast Leaves for Programmer Art

### PR DESCRIPTION
**Pull request by NebelNidas**
306f45287f6ec86b73f88def279e1ca20fe17770, but for Programmer Art. I also copied the license file again just to be sure.

<details>
<summary>Before</summary>

</details>

<details>
<summary>After</summary>

</details>

Due to a bug in Fabric's Resource Loader (which I fixed today), this feature only works with Fabric API 0.85+; on previous versions it has no effect at all.

### CODE REVIEW

**Comment by NebelNidas** [comment]
Hmm, the jungle leaves still look out of place, as if they haven't changed at all. Maybe the VanillaTweaks team accidentally bundled up an incorrect version? Doesn't seem implausible, since the modification dates are May of this year. Maybe you can ask them beforehand, @IMS212?

**Comment by mrjasonn** [comment]
Please remember to make sure this is with vanilla parity because they seem to look a bit off @NebelNidas @jellysquid3

**Comment by NebelNidas** [comment]
It unfortunately will never have a 100% visual parity to vanilla, since Sodium is interfering with leaf rendering ever since version 0.4.10. That's why I've made this PR in the first place, so it at least better resembles vanilla (take a look at my first screenshot, that's how it looks in the current release version)

**Comment by mrjasonn** [comment]
> It unfortunately will never have a 100% visual parity to vanilla, since Sodium is interfering with leaf rendering ever since version 0.4.10. That's why I've made this PR in the first place, so it at least better resembles vanilla (take a look at my first screenshot, that's how it looks in the current release version)

@NebelNidas It is very important to have Sodium be wiith vanilla parity. If you haven't yet, please check in vanilla Minecraft and make sure the textures you are providing is with parity with the vanilla Programmer Art texture pack and I'd like to see it with vanilla parity and probably everyone else as well. Thanks!

**Comment by Fnige** [comment]
Honestly it looks close enough to vanilla parity for it to be fine

**Comment by mrjasonn** [comment]
> Honestly it looks close enough to vanilla parity for it to be fine

Well it's still a vanilla parity issue so it deserves fixing.

**Comment by IMS212** [comment]
Sodium is not intended to have full vanilla parity, the texture change is required to fix this issue. I’ll ask if the textures are broken before merging.

**Comment by mrjasonn** [comment]
> Sodium is not intended to have full vanilla parity, the texture change is required to fix this issue. I’ll ask if the textures are broken before merging.

Ok. Also please note we can use VanillaTweak's methods and make our own that resembles vanilla more @IMS212.

**Comment by mrjasonn** [comment]
And the Sodium Modrinth page says this:

> Sodium is a free and open-source mod for Minecraft 1.16+ clients which greatly improves rendering performance while fixing some graphical issues. It boasts wide compatibility with the Fabric mod ecosystem when compared to other rendering-focused mods, and it does so without compromising on how the game looks, giving you that authentic block game feel.

This essentially means Sodium should have good enough vanilla parity. Especially with the Programmer Art pack, it shows the history of the game's textures. @IMS212

**Review by IMS212 — APPROVED** [review]
LGTM

**Comment by IMS212** [comment]
Actually, not sure... going to leave this for now while I confirm.

**Comment by IMS212** [comment]
Merged manually with a custom jungle leaves texture to fix VT's broken one.

**Pull request closed without merging**
