### PR TITLE
Update Loom Version

### PR DESCRIPTION
**Pull request by DragonEggBedrockBreaking**
Mods don't seem to build anymore on loom 0.5, so I updated it to 0.6. PRs coming on Lithium, Phosphor and Hydrogen soon™️.

### CODE REVIEW

**Comment by jellysquid3** [comment]
Can you please explain the issue Loom 0.5 is having? I've not seen any problems and I do not understand why the toolchain would suddenly stop working.

**Comment by DragonEggBedrockBreaking** [comment]
> Can you please explain the issue Loom 0.5 is having? I've not seen any problems and I do not understand why the toolchain would suddenly stop working.

I was doing some stuff on my fork (not important, check if you want), and GitHub Actions failed, and it also failed on AuroraDecorations (mod by LambdAurora). To quote her:

> Switch to loom 0.6 because some random ass corporation decided to shut down a maven repository used by a lot of people.

Source: https://github.com/LambdAurora/AurorasDecorations/commit/b64a0c80dad95fbcf96d1a949148f03d28430684

**Comment by magneticflux-** [comment]
> Switch to loom 0.6 because some random ass corporation decided to shut down a maven repository used by a lot of people.

The repo in question is JCenter/Bintray, and it's not shut down _yet_, but will be in the future. As of now, Modmuss recommends Loom 0.6: https://modmuss50.me/fabric.html which includes this commit: https://github.com/FabricMC/fabric-loom/commit/c95e3459a400077964e5d9ed52392b77330487ba

**Comment by DragonEggBedrockBreaking** [comment]
> and it's not shut down _yet_

Then why are builds already failing?

**Comment by magneticflux-** [comment]
The build in question (https://github.com/LambdAurora/AurorasDecorations/runs/2113994351) failed because of this: https://status.bintray.com/incidents/ctv4bdfz08bg.

It's just an unlucky coincidence.

**Comment by DragonEggBedrockBreaking** [comment]
> The build in question (https://github.com/LambdAurora/AurorasDecorations/runs/2113994351) failed because of this: https://status.bintray.com/incidents/ctv4bdfz08bg.
> 
> It's just an unlucky coincidence.

Oh, OK. I will keep this open, and JellySquid can decide if she wants to merge or just close (for now).

**Comment by LambdAurora** [comment]
> I was doing some stuff on my fork (not important, check if you want), and GitHub Actions failed, and it also failed on AuroraDecorations (mod by LambdAurora). To quote her:
> 
> > Switch to loom 0.6 because some random ass corporation decided to shut down a maven repository used by a lot of people.
> 
> Source: [LambdAurora/AurorasDecorations@b64a0c8](https://github.com/LambdAurora/AurorasDecorations/commit/b64a0c80dad95fbcf96d1a949148f03d28430684)

To be honest, this was totally an overreaction on my part.

Issues with jcenter should not happen before February 2022. Today was an incident as already mentionned.

**Comment by DragonEggBedrockBreaking** [comment]
update: this seems to still be an issue, and i am observing that some mods are still not building correctly (with loom <= 0.5), therefore this is not just future-proofing, but is still fixing a current build issue

**Comment by jellysquid3** [comment]
Resolved with 5545895.

**Pull request closed without merging**
