### PR TITLE
Reworked leaves textures as well as adding waterlogging support.

### PR DESCRIPTION
**Pull request by TheNukeLore**
Remade the better leaf system from scratch, and alongside that, I included an experimental waterlogging system that helps people visually see waterlogged leaves with fast graphics.

What's currently included:

* Support for all leaves
* Waterlogged blockstates for leaves
* Programmer art leaves

Known and/or potential issues:

* Waterlogged leaves texture will likely override other resource packs texture unless they specifically add waterlogging support to said pack.
* Waterlogged programmer art leaves revert back to non-programmer art leaves due to the issue mentioned above.

Something to note: For packs to add support for waterlogged leaves, they will need to add a folder called "``waterlogged``" in "``textures/block/``". In that folder, they can add their own form of waterlogged leaves or simply copy their existing texture there if they don't care to support waterlogged leaves on fast graphics.

When it comes to models, most models should simply work, as they are only replacing the texture. There is a niche case where it could still break, but it is extremely unlikely.

If requested, I may remove waterlogged support due to the issues that it can cause.

### CODE REVIEW

**Comment by TheNukeLore** [comment]
These changes:

Current sodium(uses vanilla tweaks leaves): 

There is partial support for programmer art leaves. however they have a few issues when it comes to water-logging, may look back into that issue as it also affects external packs. image showing the issue at hand: 

Should be noted that non of my changes copy or use assets from Vanilla Tweaks, these are all manually made using the base leaf textures.

**Comment by jellysquid3** [comment]
I'm not okay with breaking resource pack compatibility for adding waterlogged textures into the game. For the most part, we don't even encourage using _Fast Graphics_ mode since it offers little to no performance improvement and introduces all kinds of issues with texture handling.

**Comment by jellysquid3** [comment]
That said, can you please elaborate on how you "improved" the existing textures? I don't see much of a difference from the screenshots given. There are bugs like #2422 but I don't actually understand what is described or if your pull request fixes this.

**Comment by TheNukeLore** [comment]
My textures are not inherently better just done in a consistent method, They were more so made in a methodology that avoided copying any part of vanilla tweaks to avoid any potential concerns of copying(cleanroom per say), however the programmer art leaves should be the most updated ones possible, they uses the latest assets from programmer art in 1.20.6. I can update this pr with the removal of water logging blockstates/textures if you still would like the other aspects.

**Comment by jellysquid3** [comment]
If you can create a new pull request with just the changes that update the Leaves textures, that would be appreciated. Let's not change the purpose of this pull request in case it's useful in the future.

**Comment by TheNukeLore** [comment]
That includes both regular and programmer art textures correct?

**Comment by jellysquid3** [comment]
Yes, both sets of textures.

**Comment by jellysquid3** [comment]
There seems to be no tangible difference between the resources in this pull request and the ones in trunk right now. And we are not interested in adding waterlogged textures for Fast graphics, since this would technically be new functionality, and would change aesthetics significantly.

**Pull request closed without merging**
