### PR TITLE
Eliminate the one-client-world assumption.

### PR DESCRIPTION
**Pull request by qouteall**
For Immersive Portals compatibility.

### CODE REVIEW

**Review by coderbot16 — APPROVED** [review]
This change looks good on its own. That being said - does Immersive Portals try to delete / release instances of WorldRenderer, and if so, how does it ensure that the underlying resources are properly released and not leaked?

**Comment by qouteall** [comment]
@coderbot16 Thanks for informing this, I will check it

**Comment by Nhoid** [comment]
Someone help me, i don't know how to install this build in my minecraft.

**Comment by Leo40Git** [comment]
@Nhoid: Don't.

**Review by jellysquid3 — APPROVED** [review]

**Review by jellysquid3 — APPROVED** [review]

**Pull request merged**
