### PR TITLE
An option to disable the ingame hurtcam

### PR DESCRIPTION
**Pull request by eatmyvenom**
This is to make it so if the player wants to not be disturbed by the ingame hurtcam while they might take damage, they can disable it here.

### CODE REVIEW

**Comment by liach** [comment]
Hmm, I wonder how this relates to optimizing the game

**Comment by eatmyvenom** [comment]
> Hmm, I wonder how this relates to optimizing the game

This is here as a feature that could be added in this mod. Not all of it pure optimizations, such as the smooth lighting (which is a fix) or the ability to disable the vignette. Overall no its not quite an optimization but rather a nice to have and ultimately is jelly's decision whether to include things like this in her mod. I'm simply doing this as a easy way for her to add this kinda stuff.

**Comment by TheGlitch76** [comment]
This looks like a cheat and would give you an edge in PVE and PVP.

**Comment by jellysquid3** [comment]
I agree with the idea that this could be used to give players an unfair advantage, however we do already include an option to disable the in-game fog (even though it's so cheap that I seriously doubt it makes any difference on hardware made after 2009...) That option is also up for similar debate.

Anyways, as per the other closure, these kind of features are better suited (in my opinion) to a standalone Fabric micro-mod to help prevent feature creep.

**Pull request closed without merging**
