### PR TITLE
Update to Minecraft 1.16.5

### PR DESCRIPTION
**Pull request by 116s**
This should update sodium to 1.16.5.

This need to be tested more. (Currently testing it)

- [x] Faced no problems

### CODE REVIEW

**Comment by HinataKato** [comment]
Not working for me, downloaded from ci, fabric-loader-0.11.1 fabric-api-0.29.3
```
Exception in thread "main" java.lang.RuntimeException: Failed to read accessWidener file from mod sodium
	at net.fabricmc.loader.FabricLoader.loadAccessWideners(FabricLoader.java:443)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: java.lang.RuntimeException: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:47)
	at net.fabricmc.loader.FabricLoader.loadAccessWideners(FabricLoader.java:441)
	... 2 more
```

**Comment by 116s** [comment]
Strange It built fine here. Going to look at it again when I get home.

**Comment by amnotbananaama** [comment]
@HinataKato You’re using the incorrect JAR file. You’re currently using `sodium-fabric-mc1.16.5-0.1.1-SNAPSHOT-dev.jar` which is intended for development environments. You want `sodium-fabric-mc1.16.5-0.1.1-SNAPSHOT.jar`

**Comment by HinataKato** [comment]
> @HinataKato You’re using the incorrect JAR file. You’re currently using `sodium-fabric-mc1.16.5-0.1.1-SNAPSHOT-dev.jar` which is intended for development environments. You want `sodium-fabric-mc1.16.5-0.1.1-SNAPSHOT.jar`

The game crashes directly after entering to the main menu

https://gist.githubusercontent.com/HinataKato/d7da9e3f20c60e2fa2767720b0e1cab5/raw/55f2c50a08506bf5030fecf37e3a90c1f40d8834/crash

**Comment by amnotbananaama** [comment]
Now you’re encountering #16. You’ll need to either build with Java 8 or run Minecraft with Java 9+. 

Note that this PR fundamentally makes no code changes. `isHeightInvalid` and `isOutOfBuildLimitVertically` both refer to the same intermediary method `method_8476`. **Any issues or bugs you encounter will also be present in the current `1.16.x/next` branch.** (Note that the 0.1 release of Sodium for 1.16.3 remains compatible with 1.16.5).

**Comment by HinataKato** [comment]
> Now you’re encountering #16. You’ll need to either build with Java 8 or run Minecraft with Java 9+.
> 
> Note that this PR fundamentally makes no code changes. `isHeightInvalid` and `isOutOfBuildLimitVertically` both refer to the same intermediary method `method_8476`. **Any issues or bugs you encounter will also be present in the current `1.16.x/next` branch.** (Note that the 0.1 release of Sodium for 1.16.3 remains compatible with 1.16.5).

I installed jdk15 and it works, thanks!

**Comment by silversquirl** [comment]
I don't see any reason to update the mappings at this point. Sodium already supports 1.16.5

**Comment by jellysquid3** [comment]
Resolved with 0d74b67.

**Pull request closed without merging**
