### PR TITLE
Implement missing graphics sliders

### LINKED ISSUE #46: Missing vanilla graphics settings
### Expected Behavior
Expected all vanilla graphics settings to be available in Sodium.

### Actual Behavior
The following graphics settings are missing:

- [ ] Fullscreen Resolution
- [ ] Distortion Effects
- [ ] FOV Effects
- [x] Entity Shadows
- [x] Entity Distance

### Reproduction Steps

1. Open Minecraft with Sodium, Settings > Video Settings...
2. Open vanilla Minecraft, Settings > Video Settings...
3. Compare the settings

### Attachments
N/A

### System Information

- Java Version: 14.0.1 64bit
- CPU: i7-1065G7
- GPU: Mesa Iris Plus Graphics

### PR DESCRIPTION
**Pull request by Madis0**
Implements:

- Fullscreen Resolution slider (ported from Sodium Extra [with permission](https://discord.com/channels/748363294749753484/812215092510195732/903737556481474630) [(via)](https://discord.gg/TBGGM9VzH9); code slightly simplified)
- Distortion Effects slider (vanilla name and tooltip)
- FOV Effects slider (vanilla name and tooltip)
- Increases the width of option groups from 200 to 250 to make Fullscreen Resolution and Max Pre-Rendered Frames phrases fit better

Fixes #46, therefore finally giving Sodium settings parity with all vanilla sliders!

**Note:** Draft PR because
* FOV and Distortion Effects sliders have a slight rounding error compared to vanilla's. I tried using Math.round and Math.floor in several ways with no luck. 
*  "max pre-rendered frames" gets abbrevated on hover and "fullscreen resolution" doesn't... Should make it the opposite now but I haven't found the reason for abbreviation.

Help is appreciated.

### CODE REVIEW

**Comment by MeeniMc** [comment]
Fullscreen slider has no effect for me. That is, I can move it, but it doesn't change the resolution. (the shift-P vanilla slider is also 'moved', but I have to reclick the slider in the vanilla interface for it to actually register that something changed and have the resolution actually switch).

When the fullscreen slider is actuated, it shows the index of the resolution in the resolution table, this is very hard to use (for example, 1920x1080@60 is number 45, 1920x1080@59 is 46, 1920x1080@30 is 47, etc, I have 157 different resolutions possible, this is hard to pick one in particular this way, especially since the left-right arrows cannot be use to move 1 by 1).

**Comment by FlashyReese** [comment]
You will need to create a new OptionFlag for resolution changes. I used the `REQUIRES_GAME_RESTART` because it was unused. For reference see https://github.com/FlashyReese/sodium-extra-fabric/commit/af0372f3267dcc213dffb4cb37790c3e9de01a48#diff-da593c2964e4899b29d79fef5122edc57411a0678e56201df310d10658b5d03dR39-R45

**Comment by Madis0** [comment]
Thanks for the feedback, I've fixed the applying and the value is now shown on hover as well.
Now I need to figure out how "max pre-rendered frames" gets abbrevated on hover and "fullscreen resolution" doesn't...

**Comment by MeeniMc** [comment]
Cool this is now working much better, there is however still a graphical problem with the resolution slider: when in use the text overlaps:

**Comment by BeansBeefBroccoli** [comment]
@MeeniMc, idk, but that error might be with whatever font it using.

**Comment by Madis0** [comment]
Well, I did mention this...

> Now I need to figure out how "max pre-rendered frames" gets abbrevated on hover and "fullscreen resolution" doesn't...

**Comment by Eiion** [comment]
Just curious, is someone still working on the issues or is further development on this currently abandoned?

**Comment by Madis0** [comment]
> Just curious, is someone still working on the issues or is further development on this currently abandoned?

Currently abandoned, feel free to take over.

**Comment by Eiion** [comment]
I wish I could. I can only offer to help with testing things but I can't code.

**Comment by douira** [comment]
If there is still interest in this, the branch this is targeting needs to be changed and then it could be reopened. This was only closed because branches were consolidated which resulted in PRs targeting those branches being closed automatically. However, if this PR is outdated or obsolete for other reasons it can just stay closed as it is.

**Pull request closed without merging**
