### PR TITLE
Can you please add a 'Remove Fog'

### PR DESCRIPTION
**Pull request by zLauch**
Can you please add a 'Remove Fog' like Optifine has so we can activate and disable fog (higher view in the nether for example)

### CODE REVIEW

**Comment by Kroppeb** [comment]
The nether fog is considered a gameplay feature, and an option to remove it will not be provided by Sodium itself. 
IIRC [Clearview](https://www.curseforge.com/minecraft/mc-mods/clearview) provides this functionality and *should* be compatible.

**Comment by zLauch** [comment]
So… The Clearview Modi s too op (lava and water)… I just downloaded  the NoFog Mod (https://www.curseforge.com/minecraft/mc-mods/nofog) and everything is working fine. Thanks for fast the awnser.

 

Von: Kroppeb <notifications@github.com> 
Gesendet: Sonntag, 2. August 2020 18:48
An: jellysquid3/sodium-fabric <sodium-fabric@noreply.github.com>
Cc: zLauch <misterlaberlaber2.0@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [jellysquid3/sodium-fabric] Can you please add a 'Remove Fog' (#225)

 

The nether fog is considered a gameplay feature, and an option to remove it will not be provided by Sodium itself.
IIRC Clearview <https://www.curseforge.com/minecraft/mc-mods/clearview>  provides this functionality and should be compatible.

**Comment by Titaniumtown** [comment]
Why is this in the form of a PR???

**Comment by jellysquid3** [comment]
Please do not use PRs to ask questions. This will result in you being banned from contributing to the repository next time.

**Pull request closed without merging**
