### PR TITLE
Optimizations to vanilla block models

### LINKED ISSUE #2460: Optimize some of vanilla's block models
### Request Description

Several blocks in vanilla use models that are very unoptimized, using far more texture planes than are strictly needed to achieve said appearance. We can get a visually identical result using less planes - the recent fix for issues like #1316 should eliminate any subpixel discrepancies that would otherwise exist in vanilla.

However, I'm not sure if including these optimized models in Sodium would jeopardise their implementation into vanilla for licensing reasons.

Affected models:
- Stairs (https://bugs.mojang.com/browse/MC-262461)
- Cauldrons (https://bugs.mojang.com/browse/MC-262470)
- Item frames (https://bugs.mojang.com/browse/MC-262527)
- Chorus flowers (https://bugs.mojang.com/browse/MC-262641)
- Hanging mangrove propagules (https://bugs.mojang.com/browse/MC-262689)
- Composters (https://bugs.mojang.com/browse/MC-267127)

The following fixes would also change texture mapping, which may be undesirable (even if vanilla's is wrong):
- Dragon egg (https://bugs.mojang.com/browse/MC-262652)
- Fence gates (https://bugs.mojang.com/browse/MC-262953)
- Fences (https://bugs.mojang.com/browse/MC-267281)
- Glass panes (https://bugs.mojang.com/browse/MC-267315)

Hoppers (https://bugs.mojang.com/browse/MC-262452) would require unused pixels to be removed from the top texture (https://bugs.mojang.com/browse/MC-262454). In addition, optimizing flower pots may require redoing how the texture works entirely, which might be bad news for mods that add their own potted objects based on the vanilla model (https://bugs.mojang.com/browse/MC-262427).

### PR DESCRIPTION
**Pull request by muzikbike**
Fixes #2460.

Models optimized so far:
- Stairs (straight and inner)
- Hoppers (down and horizontal)
- Composter
- Chorus flower
- Turtle eggs of stack size 4
- Candle cakes
- Anvil
- Beacon
- Item frame, with or without map
- Hanging lantern
- Hanging mangrove propagule

Models I'm still to do:
- Dragon egg
- Flower pots and potted objects
- Cauldron

See #2460 for explanations of these optimizations as well as performance comparisons.

### CODE REVIEW

**Comment by mrjasonn** [comment]
Wouldn't doing ones that fix custom texture mapping break some custom resource packs which are adapted to the fact that they have broken texture mapping? If that is the case, shouldn't we just optimise it and remember to keep them looking the same as vanilla? (the looking same as vanilla should also be for everything in this PR)

**Comment by mrjasonn** [comment]
And if we are using the attached resource packs in the Mojiras to optimise the models, shouldn't we have a credits thanking them for their work?

**Comment by mrjasonn** [comment]
> ...and for the rest (item frames, propagules) nobody will notice the difference and if they do they won't care....

Please just make them look vanilla (I don't mind them looking different if clip in in spectator mode), as people might want them to actually look vanilla and not just ignore the fact it doesn't look vanilla. You have said that fixes for #1316 and #1902 may make this not visible, so please test on top of those commits. If it is harder to see, still best to keep vanilla in my opinion.

**Comment by jellysquid3** [comment]
> And if we are using the attached resource packs in the Mojiras to optimise the models...

As far as I know, this is Muzikbike's original work. If it's not, then we need to know, since we require that all contributions be the submitter's original work...

**Comment by jellysquid3** [comment]
The changes seem fine to me. The minor details you mentioned are very unlikely to cause issues. But, for us to import these into the repository, each model file should probably have documentation (in the form of a `__comment` line at least) explaining what changes were made from Vanilla.

**Comment by jellysquid3** [comment]
@muzikbike Do you have any update on this? I'd like to merge it if you think it's ready. The only remaining blocks that don't appear to be addressed by this pull request are not so common in the world anyways (Dragon Eggs, Flower Pots, Cauldrons...), so the performance impact of improving them is very, very small.

**Comment by djmrFunnyMan** [comment]
Apparently dragon eggs got optimized ([MC-262652](https://bugs.mojang.com/browse/MC-262652) was fixed) in the latest snapshot

**Comment by muzikbike** [comment]
I'd prefer to finish optimizing the remaining blocks. Cauldrons are a major offender and show up in a good handful of farms, so those are a priority to fix.

**Comment by mrjasonn** [comment]
@jellysquid3, if this gets done in time, would this be something that potentially gets added in Sodium 0.6?

**Comment by jellysquid3** [comment]
Uhh... If the pull request was ready in the day or so, then yes, we could package it for Sodium 0.6.0. But the timeline on that is likely to be too close.

It's also not necessary to have all block models addressed in the initial pull request, if those need more time. We can always follow up with another pull request later down the road.

**Comment by muzikbike** [comment]
I should be able to do cauldrons in a later PR if people want this in 0.6. What else needs done before I can consider this ready?

**Comment by jellysquid3** [comment]
There is nothing blocking this pull request on our side. But while it is marked as a draft we cannot do anything with it.

**Review by jellysquid3 — CHANGES_REQUESTED** [review]
There are many issues with inconsistent formatting and indentation in this pull request. Can you please run the files through a JSON formatter to normalize everything? We use 4-wide spaces in the project, so that should be used here too.

**Comment by muzikbike** [comment]
Just threw everything into Blockbench and exported it. Does this suffice?

**Comment by jellysquid3** [comment]
I've merged the changes manually with https://github.com/CaffeineMC/sodium/commit/d3aed21458560384abbac9e47dcaa096112aa910 to accommodate code style requirements, and because your branch was not tracking the multiloader changes.

Thank you for your efforts.

**Pull request closed without merging**
