### PR TITLE
Update Actions, Gradle and Deps

### PR DESCRIPTION
**Pull request by CanerKaraca23**

### CODE REVIEW

**Comment by IMS212** [comment]
This is not fully updated; there is a more efficient way to setup Gradle in Github Actions. I will make a commit soon to add this.

**Comment by CanerKaraca23** [comment]
> This is not fully updated; there is a more efficient way to setup Gradle in Github Actions. I will make a commit soon to add this.

So, what about other changes? At least you can edit PR and wait, why immediately close.

**Comment by IMS212** [comment]
I have applied all the changes + a new Gradle action as of a few minutes ago.

**Comment by CanerKaraca23** [comment]
> I have applied all the changes + a new Gradle action as of a few minutes ago.

Some action versions left, like upload.

**Pull request closed without merging**
