### PR TITLE
Add Mouse Scroll Support for SliderControl

### PR DESCRIPTION
**Pull request by FlashyReese**
Just a quality of life change to address #113 

- Added Mouse Scroll Support for SliderControl.

### CODE REVIEW

**Comment by jellysquid3** [comment]
My biggest concern with this is that in the near future, the list of options will grow enough to necessitate a scroll bar in order to cover everything. This would create overlapping scroll areas and make things rather non-intuitive when users want to scroll down the list, since random sliders would get adjusted instead. Need to think on it.

**Comment by luximus-hunter** [comment]
It could prioritize the slider scroll over the vertical scrolling. But that's just my mind speaking 🤷‍♂️

**Comment by FlashyReese** [comment]
It would depend on how the widget list box is implemented. It shouldn't be a problem(for now).

**Comment by blai30** [comment]
I agree with Jelly here, UI/UX is important. I wouldn't want to be scrolling through the settings only to accidentally change something. If anything I would rather it be shift + scrollwheel.

**Comment by FlashyReese** [comment]
I forgot to point out that this feature only scrolls while within sliderbounds. I will be looking into implement a scrollable list(as the list of settings grow) to address those concerns.

**Pull request closed without merging**
