### PR TITLE
Change layout of settings menu

### PR DESCRIPTION
**Pull request by FlashyReese**
This PR makes the following changes:
- Added Mouse Scroll Support for SliderControl.
- Fixes Missing Translations Strings in SodiumGameOptionPages and SodiumGameOptions
- Added TabControlScrollPaneWidget exclusively for OptionPages
     - Also addresses current issue with localizations
     - Also adds scrollbar support (to address concerns with a growing settings menu)

Addresses the following:
- #113 
- #115 

Preview: https://youtu.be/mKzq4oIqF0s

### CODE REVIEW

**Comment by Madis0** [comment]
It seems like the performance impact is no longer displayed in the tooltip? 
Also, for sidebar tabs I'd suggest a blue rectangle around the button, not just a line below.

**Comment by Titaniumtown** [comment]
I think it looks nice!

**Comment by FlashyReese** [comment]
> It seems like the performance impact is no longer displayed in the tooltip?
> Also, for sidebar tabs I'd suggest a blue rectangle around the button, not just a line below.

Performance impact was removed by Jelly on the dev branch.
I will look into that when Jelly moves these mods into an org, she is currently deciding on a name.

**Comment by FlashyReese** [comment]
Superseded by #293

**Pull request closed without merging**
