### PR TITLE
Compatibility with Immersive Portals in the "next" branch

### PR DESCRIPTION
**Pull request by qouteall**
One thing that you may not like is the "duplicated" vertex shader. Because to use the gl_ClipDistance feature the glsl version must be at least 130. But upgrading the shader file version may cause incompatibility with older devices. So I made it switch to the clipping vertex shader only when IP is present and keep the old-versioned shader.

### CODE REVIEW

**Comment by DragonEggBedrockBreaking** [comment]
You forgot to mention:
Fixes #15

**Comment by srnyx** [comment]
@comp500 Could you implement this into your fork?

**Comment by comp500** [comment]
@srnyx No. My change is trivial to merge into qouteall's fork, just [edit the single line](https://github.com/comp500/sodium-fabric/commit/8cbe9ebc04df818b82b8af218c853c50fef64d89) yourself.

**Comment by machinesmith42** [comment]
@srnyx  my build contains that fix

**Pull request closed without merging**
