### PR TITLE
Add Swedish Translation

### PR DESCRIPTION
**Pull request by Dontknow09**
### Changes
All options are translated to Swedish and saved as sv_se.json

### CODE REVIEW

**Comment by Felix14-v2** [comment]
Currently translations should be created here:
https://crowdin.com/project/sodium-fabric

**Comment by Dontknow09** [comment]
Do you want me to fix it?

**Comment by Felix14-v2** [comment]
I mean this PR most likely will not be merged, internationalization is not a not a priority task for Sodium at the current stage. But you can [submit your translations on Crowdin](https://crowdin.com/translate/sodium-fabric/37/en-sv) and play with them by installing this resource pack:
https://modrinth.com/resourcepack/translations-for-sodium

**Comment by Dontknow09** [comment]
Ok should I close the PR?

**Comment by Felix14-v2** [comment]
If you want ¯\\\_(ツ)_/¯
Personally I didn't close my one just to notify people that translations already done, and they don't need to waste time on work already done. Anyway, not everyone checks the closed PR section before creating their own.

**Comment by Dontknow09** [comment]
Why does Crowdin need my email if I use Github?

**Comment by Madis0** [comment]
> Why does Crowdin need my email if I use Github?

From their account page:

> Not publicly visible. Email will be used for account-related notifications (e.g., password resets, project activity updates, and invitations to projects). [Customize.](https://crowdin.com/settings#user-profile-notifications)

For this context specifically, you can choose to get notifications every time new strings are added or changed in the Sodium translations project.

**Comment by jellysquid3** [comment]
We don't currently accept translations upstream yet. But you can contribute to the community-driven translations project above.

**Pull request closed without merging**
