### PR TITLE
Compare perspective matrix when marking graph as dirty

### PR DESCRIPTION
**Pull request by MCRcortex**

### CODE REVIEW

**Comment by douira** [comment]
Is it still necessary to compare the camera angle (and position too?) if the projection matrix is compared?

**Comment by MCRcortex** [comment]
Projection matrix doesnt contain the camera transform

**Comment by douira** [comment]
Ok, then lgtm.

**Review by jellysquid3 — APPROVED** [review]
This change looks fine to me. But in the future, we should look at creating a record object to hold this state so that we don't have this complex if-statement.

**Review by IMS212 — APPROVED** [review]
Looks good to me.

**Pull request merged**
