### PR TITLE
remove redundant chmod +x gradlew

### PR DESCRIPTION
**Pull request by deltanedas**
CI adds the execute bit to `gradlew`.
Screenshot_14:15:19

I simply removed these two lines as it's already set.

### CODE REVIEW

**Comment by liach** [comment]
Don't think it's done by the ci. You can just do `git update-index --chmod +x gradlew` to change file mode for git

**Comment by deltanedas** [comment]
it's already executable, ci doesn't need to make it so.

**Comment by LucilleTea** [comment]
Does this change actually have any benefit? It seems like you're removing something that's harmless at worst, and a helpful failsafe if it needs to be. I don't see any reason to do that.

**Comment by magneticflux-** [comment]
It's akin to fixing a spelling mistake. It doesn't cause any harm either way.

**Comment by ImperatorStorm** [comment]
Fixing a spelling mistake is correct something wrong.

This, i'd say, is more akin to removing a redundancy.

**Comment by jellysquid3** [comment]
Yes, the bits are already set in Git source tree. There is no reason for the action to be setting the executable bit, and removing the build step to do so is fine. It's just part of the original action template and exists for Windows users without unix-style permissions.

Anyways. Parkinson's law of triviality strikes again. Thank you for your PR -- this is attention to detail, even if it's a small change.

**Review by jellysquid3 — APPROVED** [review]

**Pull request merged**
