### PR TITLE
Translucency sort using compute shaders

### LINKED ISSUE #38: Translucent blocks do not render correctly (fixed in Sodium 0.6)
### Expected Behavior
Water will be visible inside glass stained pipes, commonly used in water elevators

### Actual Behavior
Water is not visible through stained glasses, although items can be seen flowing

### Reproduction Steps
Make a water tube, doesn't matter if its flowing or a water elevator type.

### Attachments
https://cdn.discordapp.com/attachments/389371678859460611/726798724206166066/received_707934516451025.png

### System Information
- Java Version: [Java 8 Update 251]
- CPU: [Intel Core i5-7200U]
- GPU: [Intel HD Graphics 620]

### PR DESCRIPTION
**Pull request by MESLewis**
Fixes #38 for supported hardware

Adds support for sorting translucent geometry by using OpenGL compute shaders.

Either OpenGL 4.3+ or OpenGL 4.2+ with both `ARB_shader_storage_buffer_object` and `ARB_compute_shader` is required for this option to function.

Before (note that some parts of slime blocks and stained glass are not drawn):

After (all translucent geometry is sorted so it is drawn correctly):

Note: Region draw order is sometimes incorrect. This is existing behavior not caused by these changes.

### CODE REVIEW

**Comment by tr7zw** [comment]
Gave it a quick try: it's able to be just merged into the 1.18 branch without changes/conflicts, and from some quick testing, it seems to be fully working as well. 👍 
Edit: Noteworthy: has some issue with the current release of iris.

**Comment by amnotbananaama** [comment]
Copying Jelly's comments on this PR [from discord](https://discord.com/channels/602796788608401408/908399790839177216/915777405220696154) for  accessibility:
  
> Thinking about it for some time, I've created more or less the following work list for getting this work into upstream:
> - Change the renderer to only care about quads, not triangles, so that you can simplify your sorting code & fix a few edge cases that vanilla handles correctly (important)
> - At some point we thought mods might care about triangle meshes but I don't see any reason to support this.
> - This also allows for some important optimizations that might happen in the future.
> - We have to deal quads anyways for FREX/FRAPI. So this needs to change.
> - Import the changes to ThinGL from 0.4-experiments so we can provide a cleaner API interface for compute shaders (refactor)
> - Move the compute code out of the chunk renderer and into new classes for occlusion culling/render list building (refactor)
> - Investigate a CPU-side fallback for the compute shader (very low priority)  
>
> Otherwise for the code itself, you've done a great job here and I don't have any complaints with that much. We just need to provide better facilities in Sodium for handling this.

**Comment by MeeniMc** [comment]
Currently requires the following patch to compile when rebased on 1.18.x/dev
```
diff --git a/src/main/java/me/jellysquid/mods/sodium/client/render/chunk/RegionChunkRenderer.java b/src/main/java/me/jellysquid/mods/sodium/client/render/chunk/RegionChunkRenderer.java
index cb9b975..7383043 100644
--- a/src/main/java/me/jellysquid/mods/sodium/client/render/chunk/RegionChunkRenderer.java
+++ b/src/main/java/me/jellysquid/mods/sodium/client/render/chunk/RegionChunkRenderer.java
@@ -114,8 +114,7 @@ public class RegionChunkRenderer extends ShaderChunkRenderer {
                         float y = getCameraTranslation(region.getOriginY(), camera.blockY, camera.deltaY);
                         float z = getCameraTranslation(region.getOriginZ(), camera.blockZ, camera.deltaZ);

-                        Matrix4f matrix = this.cachedModelViewMatrix;
-                        matrix.set(matrices.modelView());
+                        Matrix4f matrix = new Matrix4f(matrices.modelView());
                         matrix.translate(x, y, z);

                         compute.setModelViewMatrix(matrix);

```

Note that this may cause some allocation overhead. 


Edit: do not use as-is, this patch trashes performance horribly, a solution must be found to remove  the extra allocation instead.

**Comment by GR8MonkeyPirate** [comment]
How do I add this to my game?

**Comment by ExpHP** [comment]
Hi, has any progress been made/is there anywhere to track progress on the [task list linked by amnotbananaama](https://discord.com/channels/602796788608401408/908399790839177216/915777405220696154)?  (or any other related efforts to help merge this into upstream?)

**Comment by nonetrix** [comment]
> How do I add this to my game?

Might be able to clone https://github.com/MESLewis/sodium-fabric/tree/translucency-sort and follow the build steps just be very aware it is most likely very unstable

**Comment by alvinqwq** [comment]
How do I use this？

**Comment by MeeniMc** [comment]
You can't at the moment, this was work in progress and has been left dormant, thus it is now incompatible with recent Sodium.

**Comment by DreamSt4n** [comment]
When will this be updated for 1.20? This is necessary to use Sodium at this point

**Comment by hexadecimal233** [comment]
This can be superceded by #2016 and #1687 as this will probably be no longer maintained

**Pull request closed without merging**
