### PR TITLE
Improve issue template

### LINKED ISSUE #1715: [meta] Add graphics driver version and operating system and version to bug report and crash report templates
**Is your feature request related to a problem? Please describe.**
Some issues are graphics driver version specific or OS specific and people cannot determine the cause of the issue without further information

**Describe the solution you'd like**
The template could ask for more information

**Describe alternatives you've considered**
Asking for a screenshot of F3 - if they're able to get in-game.
Asking for a screenshot of dxdiag or a dxdiag report.
Asking for logs

**Additional context**

### PR DESCRIPTION
**Pull request by Phoenix-Starlight**
Continuation of #1739, resolves #1715
>Some 'descriptions' have been set to heading 4 style to make it more noticeable, as well as addition of 2 new fields for OS version and graphics driver version.
I am not quite sure why >- is used (bullet points?), so I removed the hyphen since it seems to make no visual difference.

### CODE REVIEW

**Comment by Poopooracoocoo** [comment]
Still got quite a few concerns and questions I raised in the previous PR but there was no response. But you did address some of the things I mentioned, so I think I can assume you acknowledge them.

**Comment by Phoenix-Starlight** [comment]
Regarding the suggestion about the hint for Graphics driver, I left it as such because I didn't want people to incorrectly fill it (e.g Nvidia graphics driver instead of iGPU (Intel) driver)

**Comment by Poopooracoocoo** [comment]
Thanks derspyy

**Comment by piuvas** [comment]
could you set `1.19.3/dev` as the default branch of your fork so that the changes can be previewed through the issue tracker?

**Comment by Phoenix-Starlight** [comment]
Should be set as the default now.

**Comment by Phoenix-Starlight** [comment]
Closing to move PR to 1.20/dev

**Pull request closed without merging**
