### PR TITLE
Restricted smooth color blending only for supported blocks and fluids. Fix 895

### LINKED ISSUE #895: Blockentity with color not rendered correctly
### Version information

sodium-fabric-mc1.17.1-0.3.0+build.5

### Reproduction Steps

1.Install Sodium and another mod that has blockentity with a block color provider
2.The blockentity is rendered in a strange way

### Java version

Java 16

### CPU

Intel Core i5-10400F

### GPU

NVIDIA GeForce GTX 1650 SUPER

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ghost**
This is the porting into 1.19 of https://github.com/CaffeineMC/sodium-fabric/commit/634b11ed989482b9aab59ba45acc92ba31b97648 that fixes #895 (and #1323 that was a duplicate of #895)

I've also added a way for modders to register new blocks and fluids for smooth blending, for example if they want to add new leaves (technically the opposite of #1331 but using the experimental commit).

```java
DefaultBlockColorSettings.registerForBlending(Block block);
DefaultBlockColorSettings.registerForBlending(Fluid fluid);
```

I've also added missing 1.18 and 1.19 leaves (mangrove and azalea), and vanilla fluids in another list.

# Testing
I've tested with my mod in 1.19, specifically the tun block.

This block is a block entity with an item on its inventory, then the "liquid" inside is colored with a color provider basing on the item (the content), because of that it requires the precise block position and blending its color with other ajacent blocks make no sense.
[TunBlock.java#L235](https://github.com/devpelux/terravibe/blob/4f9cfd3b6e17cbabef534ef4e541e5739a9cbe9f/src/main/java/xyz/devpelux/terravibe/block/TunBlock.java#L235)

Normal:

With fix:

Test for supported blocks: (E.g Grass)

### CODE REVIEW

**Comment by burgerindividual** [comment]
Some variant of this *will be included* in the 0.5 release, just want to work on other things before looking into this.

**Comment by IMB11** [comment]
Suggestion, restrict color blending to blocks/fluids in the `c:blendable` tag. This would mean that any mods that want to add color blended blocks do not need to directly depend on sodium.

And FYI, tags can be read via clientside, take a look at how the F3 screen lists all tags the block your looking at is in.

**Comment by IMB11** [comment]
Id be willing to add this to the PR if wanted

**Comment by ghost** [comment]
Works good.

```java
private static int getBlockColor(BlockState state, BlockRenderView view, @NotNull BlockPos pos, int i) {
    return pos.getX() < 0 ? 0xff0000 : 0x0000ff;
}
```

**Comment by devpelux** [comment]
Any news about this?

**Comment by devpelux** [comment]
## UPDATE
I've included this fix into a mod named "Sodium Blending Registry".
It includes the `c:blendable` tag too.

**Comment by ghost** [comment]
# UPDATE
I've included this fix into a mod named "Sodium Blending Registry".
It includes the `c:blendable` tag too.

Source code: https://github.com/devpelux/sodium-blendingregistry
Mod link: https://modrinth.com/mod/sodium-blendingregistry

**Comment by ghost** [comment]
Closed.
See this: https://github.com/CaffeineMC/sodium-fabric/issues/895#issuecomment-1624127058

**Pull request closed without merging**
