### PR TITLE
Minor Changes

### PR DESCRIPTION
**Pull request by DragonEggBedrockBreaking**
I have made some small changes to some parts of the GitHub repository:

- Fixed broken link in README
- Some changes in `fabric.mod.json`

Unlike what many may expect, I did **not** set the homepage to modrinth/curseforge, and you can find my reasoning in JellySquid's comment on #379 

I set the project homepage to https://jellysquid.me/projects/ so that it would be more related to the mods.

### CODE REVIEW

**Comment by jellysquid3** [comment]
The changes here to the mod manifest are fine, but we should really just remove the bit about issue reporting from our CONTRIBUTING.md, since the issue templates make it redundant.

**Comment by DragonEggBedrockBreaking** [comment]
> The changes here to the mod manifest are fine, but we should really just remove the bit about issue reporting from our CONTRIBUTING.md, since the issue templates make it redundant.

I removed it now. Is there anything else that I need to change?

**Comment by DragonEggBedrockBreaking** [comment]
Fixed some minor consistency issues with the issue and crash report templates.

**Comment by DragonEggBedrockBreaking** [comment]
I changed `modCompile` to `modImplementation` to keep forwards compatibility with JDK 16 (which requires at least Gradle 7.0-rc1). I know that this mod currently downloads JDK 8 to build this, but since 5545895 bumps loom to 0.6, it seems that this mod's aim is to remain forwards compatible and/or up to date and/or tries to remove deprecated features. This is likely the last change I will do.

**Comment by DragonEggBedrockBreaking** [comment]
Loom 0.7-SNAPSHOT will soon be recommended, and Gradle 7.0 is now the latest stable release, but there have been a lot of deprecated features between Gradle 6 and 7, so I will not be including that change in this PR. This also applies to my PRs on Lithium, Phosphor and Hydrogen.

**Comment by DragonEggBedrockBreaking** [comment]
merged/resolved conflicts

**Comment by DragonEggBedrockBreaking** [comment]
Reverted modcompile change due to being implemented by #630 in a way that actually matters.

**Review by hxr404 — APPROVED** [review]

**Comment by DragonEggBedrockBreaking** [comment]
closing because there will not be 1.16 releases soon, i will re-do this for the 1.17 branch

**Comment by DragonEggBedrockBreaking** [comment]
on second thoughts, this PR is too trivial so I will not re-make it (feel free to manually implement some of the things i changed here)

**Pull request closed without merging**
