### PR TITLE
Respect server view distance, use new fog calculation

### PR DESCRIPTION
**Pull request by IMS212**
Seems to fix the multiple fog distance issues.

### CODE REVIEW

**Comment by IMS212** [comment]
Fog calculation is finally correctly fixed.

**Comment by dopadream** [comment]
good fucking riddance

**Comment by MeeniMc** [comment]
Tested, it works as intended; changing the server viewdistance also updates the fog distance

**Comment by KaspianDev** [comment]
Im not a big fan of this, this makes the fog too close to me on servers with small view distance

**Comment by IMS212** [comment]
Being a fan of this doesn’t matter; the question is if it matches Vanilla. We will not break what vanilla does just so a few people are happier.

**Comment by dopadream** [comment]
It's literally how fog behaves in vanilla.

**Comment by KaspianDev** [comment]
i'd like to have an option to modify it like in old versions of the game

**Comment by IMS212** [comment]
That may be added by a mod like Sodium Extra, but should not be part of the official mod.

**Review by jellysquid3 — APPROVED** [review]

**Comment by jellysquid3** [comment]
We don't intend to meaningful deviate from how vanilla renders things. Fog is a gameplay feature and we especially don't want to change that. This is supposed to be an optimization mod, not a kitchen sink of gameplay options.

**Pull request merged**
