### PR TITLE
Fix translation & add Chinese.

### PR DESCRIPTION
**Pull request by KrisCris**

### CODE REVIEW

**Comment by KrisCris** [comment]
- Fix all missing translation.
- Add a translation for zh_cn based on that.

**Comment by jellysquid3** [comment]
Translations are being added through [OneSky](jellysquid.oneskyapp.com/). You should contribute translated strings there. In the future, Sodium will automatically download these translations when building the mod.

**Comment by KrisCris** [comment]
Ah, I didn't notice that.

**Comment by KrisCris** [comment]
But I think some translations are missing in that json file, e.g. off, crosshair, Hotbar.

**Comment by FlashyReese** [comment]
Those translations are included in Minecraft itself. Take a look at #116

**Comment by Leo40Git** [comment]
Those translations are pulled from Minecraft's own translation JSON files, I'm pretty sure. Why reinvent the wheel, after all?

**Pull request closed without merging**
